logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoint.health.show-details: ALWAYS
management.endpoints.web.exposure.include: "*"

server:
  port: 8080

spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: strawman-service
          uri: http://localhost:8081
          #lb://strawman-service
          predicates:
            - Path=/userinfo/**
          filters:
            #- RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: TenantTokenFilter
              args:
                preLogger: true
                postLogger: true
  security:
    user:
      password: password

      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357
            audience: https://api.comp-score.com/connect
        client:
          registration:
            gateway:
              provider: okta
              client-id: okta.oauth2.client-id
              client-secret: okta.oauth2.client-secret
              authorized-grant-types: authorization_code
              scope: openid,profile,email,resource.read,groups
              authorities: uaa.resource
              redirect-uri: http://localhost:8080/authorization-code/callback
            provider:
              okta:
                authorization-uri: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/authorize
                token-uri: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/token
                user-info-uri: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/userinfo
                user-name-attribute: sub
                jwk-set-uri: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/keys

okta:
  oauth2:
    audience: https://api.comp-score.com/connect
    authorities: uaa.resource
    authorization_endpoint: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/authorize
    authorized-grant-types: authorization_code
    claims_supported: [
      aud,
      cid,
      exp,
      iat,
      iss,
      jti,
      scp,
      sub,
      uid,
      ver
    ]
    client-id: 0oa3z6akwh3Kr6fiJ357
    client-secret: _Vr9M3d-FM2xT9CCIajbbL72i_NBo5uRf7UwS6gT
    code_challenge_methods_supported: [
      S256
    ]
    end_session_endpoint: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/logout
    grant_types_supported: [
      authorization_code,
      client_credentials,
      implicit,
      password,
      refresh_token
    ]
    introspection_endpoint: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/introspect
    introspection_endpoint_auth_methods_supported: [
      client_secret_basic,
      client_secret_jwt,
      client_secret_post,
      none,
      private_key_jwt
    ]
    issuer: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357
    jwks_uri: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/keys
    provider: okta
    redirect-uri: http://localhost:8080/authorization-code/callback

    registration_endpoint: https://comp-score.com/oauth2/v1/clients
    request_parameter_supported: true
    request_object_signing_alg_values_supported: [
      ES256,
      ES384,
      ES512,
      HS256,
      HS384,
      HS512,
      RS256,
      RS384,
      RS512
    ]
    response_modes_supported: [
      form_post,
      fragment,
      okta_post_message,
      query
    ]
    response_types_supported: [
      "code id_token token",
      "code id_token",
      "code token",
      "code",
      "id_token token",
      "id_token",
      "token"
    ]
    revocation_endpoint: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/revoke
    revocation_endpoint_auth_methods_supported: [
      client_secret_basic,
      client_secret_jwt,
      client_secret_post,
      none,
      private_key_jwt
    ]
    scope: openid,profile,email,resource.read,groups
    scopes_supported: [
      address,
      email,
      groups,
      offline_access,
      openid,
      phone,
      profile,
      secret
    ]
    subject_types_supported: [
      public
    ]
    token_endpoint: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/token
    token_endpoint_auth_methods_supported: [
      client_secret_basic,
      client_secret_jwt,
      client_secret_post,
      none,
      private_key_jwt
    ]
    user-info-uri: https://comp-score.com/oauth2/aus2fguvpzcx7RR5A357/v1/userinfo
    user-name-attribute: sub